### ISSUE TITLE
M2T5 - Choose meaningful names

### ISSUE THREAD

**Issue by isaacborges** [tecprog-fga/SpaceShooter#7]
Module 2. technique 5

Choose meaningful names.

**Comment by adailson2** [comment]
Add commit that refereced this issue. [f22cc74](https://github.com/tecprog-fga/SpaceShooter/commit/f22cc74)

**Comment by adailson2** [comment]
Add commit that refereced this issue. [86e51b5](https://github.com/tecprog-fga/SpaceShooter/commit/86e51b5)
